### ISSUE TITLE
Fix crashers found by fuzzing

### ISSUE THREAD

**Issue by kisielk** [kisielk/og-rek#30]
```
"((dd"

panic: runtime error: hash of unhashable type map[interface {}]interface {}

goroutine 1 [running]:
github.com/kisielk/og-rek.(*Decoder).loadDict(0xc420085170, 0x64, 0x0)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:652 +0x18c
github.com/kisielk/og-rek.Decoder.Decode(0xc42001cd20, 0x5a9320, 0x0, 0x0, 0xc420016f00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:188 +0x172d
github.com/kisielk/og-rek.Fuzz(0x7f3e672e1000, 0x4, 0x200000, 0x3)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/fuzz.go:12 +0x108
go-fuzz-dep.Main(0x50d798)
        /tmp/go-fuzz-build403415384/goroot/src/go-fuzz-dep/main.go:49 +0xd9
main.main()
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/go.fuzz.main/main.go:10 +0x2d
exit status 2
"}}}s"

panic: runtime error: hash of unhashable type map[interface {}]interface {}

goroutine 1 [running]:
github.com/kisielk/og-rek.(*Decoder).loadSetItem(0xc420098000, 0xc42000a373, 0x0)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:831 +0x13b
github.com/kisielk/og-rek.Decoder.Decode(0xc42001c120, 0x5a9320, 0x0, 0x0, 0xc4200161b0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:220 +0x1a4c
github.com/kisielk/og-rek.Fuzz(0x7f0f87128000, 0x4, 0x200000, 0xc42003df78)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/fuzz.go:12 +0x108
go-fuzz-dep.Main(0x50d798)
        /tmp/go-fuzz-build403415384/goroot/src/go-fuzz-dep/main.go:49 +0xd9
main.main()
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/go.fuzz.main/main.go:10 +0x2d
exit status 2
"(((ld"

panic: runtime error: hash of unhashable type []interface {}

goroutine 1 [running]:
github.com/kisielk/og-rek.(*Decoder).loadDict(0xc4200894d0, 0x64, 0x0)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:652 +0x18c
github.com/kisielk/og-rek.Decoder.Decode(0xc42001cf60, 0x5a9320, 0x0, 0x0, 0xc420016fc0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:188 +0x172d
github.com/kisielk/og-rek.Fuzz(0x7fbfd4b96000, 0x5, 0x200000, 0x3)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/fuzz.go:12 +0x108
go-fuzz-dep.Main(0x50d798)
        /tmp/go-fuzz-build403415384/goroot/src/go-fuzz-dep/main.go:49 +0xd9
main.main()
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/go.fuzz.main/main.go:10 +0x2d
exit status 2
"}(U\x040000u"

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/kisielk/og-rek.(*Decoder).loadSetItems(0xc420088000, 0x75, 0x0)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:851 +0x250
github.com/kisielk/og-rek.Decoder.Decode(0xc42001c180, 0x5a9320, 0x0, 0x0, 0xc420016360, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:232 +0x251d
github.com/kisielk/og-rek.Fuzz(0x7f466e803000, 0x9, 0x200000, 0xc42003df78)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/fuzz.go:12 +0x108
go-fuzz-dep.Main(0x50d798)
        /tmp/go-fuzz-build403415384/goroot/src/go-fuzz-dep/main.go:49 +0xd9
main.main()
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/go.fuzz.main/main.go:10 +0x2d
exit status 2
"S\n"

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/kisielk/og-rek.(*Decoder).loadString(0xc4200882d0, 0xc420088253, 0x0)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:502 +0x469
github.com/kisielk/og-rek.Decoder.Decode(0xc42001c360, 0x5a9320, 0x0, 0x0, 0xc4200164e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:172 +0x1199
github.com/kisielk/og-rek.Fuzz(0x7f5029057000, 0x2, 0x200000, 0x3)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/fuzz.go:12 +0x108
go-fuzz-dep.Main(0x50d798)
        /tmp/go-fuzz-build403415384/goroot/src/go-fuzz-dep/main.go:49 +0xd9
main.main()
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/go.fuzz.main/main.go:10 +0x2d
exit status 2
"(\x88d"

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/kisielk/og-rek.(*Decoder).loadDict(0xc420082990, 0xc42000e464, 0x0)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:652 +0x21d
github.com/kisielk/og-rek.Decoder.Decode(0xc42001c7e0, 0x5a9320, 0x0, 0x0, 0xc4200167b0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:188 +0x172d
github.com/kisielk/og-rek.Fuzz(0x7f6d1f310000, 0x3, 0x200000, 0x3)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/fuzz.go:12 +0x108
go-fuzz-dep.Main(0x50d798)
        /tmp/go-fuzz-build403415384/goroot/src/go-fuzz-dep/main.go:49 +0xd9
main.main()
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/go.fuzz.main/main.go:10 +0x2d
exit status 2
```

**Comment by kisielk** [comment]
The original decoder code was translated from Python, which just throws exceptions for any out of bounds errors. Unfortunately those translate to panics in Go, so there's probably a few more places where we need to do stricter validation and bounds checking. Hopefully fuzzing can help us uncover a lot of those.

**Comment by navytux** [comment]
More bugs:

"(dS''\n(lp4\nsg4\n(s"

```
panic: runtime error: hash of unhashable type []interface {}

goroutine 1 [running]:
github.com/kisielk/og-rek.(*Decoder).loadSetItem(0xc420084a20, 0x73, 0x0)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:831 +0x13b
github.com/kisielk/og-rek.Decoder.Decode(0xc42001c840, 0x5a9320, 0x0, 0x0, 0xc420016a20, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:220 +0x1a4c
github.com/kisielk/og-rek.Fuzz(0x7fa3decfb000, 0x11, 0x200000, 0x3)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/fuzz.go:12 +0x108
go-fuzz-dep.Main(0x50d798)
        /tmp/go-fuzz-build403415384/goroot/src/go-fuzz-dep/main.go:49 +0xd9
main.main()
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/go.fuzz.main/main.go:10 +0x2d
exit status 2
```

"}((tu"

```
panic: runtime error: hash of unhashable type []interface {}

goroutine 1 [running]:
github.com/kisielk/og-rek.(*Decoder).loadSetItems(0xc420084d80, 0x75, 0x0)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:851 +0x1c0
github.com/kisielk/og-rek.Decoder.Decode(0xc42001ca80, 0x5a9320, 0x0, 0x0, 0xc420016db0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:232 +0x251d
github.com/kisielk/og-rek.Fuzz(0x7ff4ffd15000, 0x5, 0x200000, 0x3)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/fuzz.go:12 +0x108
go-fuzz-dep.Main(0x50d798)
        /tmp/go-fuzz-build403415384/goroot/src/go-fuzz-dep/main.go:49 +0xd9
main.main()
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/go.fuzz.main/main.go:10 +0x2d
exit status 2
```

"}((du"

```
panic: runtime error: hash of unhashable type map[interface {}]interface {}

goroutine 1 [running]:
github.com/kisielk/og-rek.(*Decoder).loadSetItems(0xc4200c4510, 0x75, 0x0)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:851 +0x1c0
github.com/kisielk/og-rek.Decoder.Decode(0xc42001d9e0, 0x5a9320, 0x0, 0x0, 0xc420017d10, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/ogorek.go:232 +0x251d
github.com/kisielk/og-rek.Fuzz(0x7fc57ff5d000, 0x5, 0x200000, 0x3)
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/fuzz.go:12 +0x108
go-fuzz-dep.Main(0x50d798)
        /tmp/go-fuzz-build403415384/goroot/src/go-fuzz-dep/main.go:49 +0xd9
main.main()
        /tmp/go-fuzz-build403415384/gopath/src/github.com/kisielk/og-rek/go.fuzz.main/main.go:10 +0x2d
exit status 2
```

**Comment by navytux** [comment]
"(c\n\nc\n\n\x85Rd"

```
panic: runtime error: hash of unhashable type ogórek.Call

goroutine 1 [running]:
github.com/kisielk/og-rek.(*Decoder).loadDict(0xc420084360, 0x64, 0x0)
        /tmp/go-fuzz-build561441550/gopath/src/github.com/kisielk/og-rek/ogorek.go:655 +0x18c
github.com/kisielk/og-rek.Decoder.Decode(0xc42001c3c0, 0x5a9300, 0x0, 0x0, 0xc4200164b0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/go-fuzz-build561441550/gopath/src/github.com/kisielk/og-rek/ogorek.go:187 +0x172b
github.com/kisielk/og-rek.Fuzz(0x7ff901592000, 0xa, 0x200000, 0x3)
        /tmp/go-fuzz-build561441550/gopath/src/github.com/kisielk/og-rek/fuzz.go:12 +0x108
go-fuzz-dep.Main(0x50d830)
        /tmp/go-fuzz-build561441550/goroot/src/go-fuzz-dep/main.go:49 +0xd9
main.main()
        /tmp/go-fuzz-build561441550/gopath/src/github.com/kisielk/og-rek/go.fuzz.main/main.go:10 +0x2d
exit status 2
```

**Comment by kisielk** [comment]
Ok looks like there's really just a couple of problems that are repeated several times.

The unhashable type one is tricky because there's not really a good way to detect whether a type is hashable or not without walking all of its members with reflect, and that's a potentially expensive operation. I wonder if the best solution would be to just recover from the panic in those cases and return an error? 

The index out of range errors in `loadSetItem` and `loadDict` just need some careful considering of the index and bounds checking before attempting to read the array.

**Comment by navytux** [comment]
about index out of range: I agree, yes, just careful index programming is needed.

about hash of unhashable types: the go spec actually requires types to be comparable to be used as map keys:

https://golang.org/ref/spec#Map_types

the runtime just calls hash first before making full equal comparision:

https://github.com/golang/go/blob/f072283b/src/runtime/alg.go#L140
https://github.com/golang/go/blob/f072283b/src/runtime/type.go#L36
https://github.com/golang/go/blob/f072283b/src/runtime/alg.go#L36

we can test whether type is comparable with reflect pretty easily via

```go
package main

import "reflect"

func comparable(v interface{}) bool {
        return reflect.TypeOf(v).Comparable()
}

func main() {
        x := 1
        y := []int{2, 3}
        z := map[string]int{"aaa": 4, "bbb": 5}
        q := struct{a, b string} {"hello", "world"}
        println(comparable(x))
        println(comparable(y))
        println(comparable(z))
        println(comparable(q))
}
```

```
true
false
false
true
```

and it does not use any recursive struct scanning as rtype.Comparable just compares 2 pointers for != nil:

https://github.com/golang/go/blob/f072283b/src/reflect/type.go#L288
https://github.com/golang/go/blob/f072283b/src/reflect/type.go#L1516

and reflect.TypeOf is just a pointer cast:

https://github.com/golang/go/blob/f072283b/src/reflect/type.go#L1405
https://github.com/golang/go/blob/f072283b/src/reflect/type.go#L3025


I would go this way instead of catching panic because

1. it is not recursively expensive
2. it is hard to make sure in long term the panic is exactly because of non-comparable types

For the reference here is to what `comparable()` currently compiles in standalone mode:

```
"".comparable t=1 size=109 args=0x18 locals=0x28
        0x0000 00000 (x.go:5)   TEXT    "".comparable(SB), $40-24
        0x0000 00000 (x.go:5)   MOVQ    (TLS), CX
        0x0009 00009 (x.go:5)   CMPQ    SP, 16(CX)
        0x000d 00013 (x.go:5)   JLS     102
        0x000f 00015 (x.go:5)   SUBQ    $40, SP
        0x0013 00019 (x.go:5)   MOVQ    BP, 32(SP)
        0x0018 00024 (x.go:5)   LEAQ    32(SP), BP
        0x001d 00029 (x.go:5)   FUNCDATA        $0, gclocals·522734ad228da40e2256ba19cf2bc72c(SB)
        0x001d 00029 (x.go:5)   FUNCDATA        $1, gclocals·e226d4ae4a7cad8835311c6a4683c14f(SB)
        0x001d 00029 (x.go:6)   MOVQ    "".v+48(FP), AX
        0x0022 00034 (x.go:6)   MOVQ    AX, reflect.i·2+16(SP)
        0x0027 00039 (x.go:6)   MOVQ    "".v+56(FP), AX
        0x002c 00044 (x.go:6)   MOVQ    AX, reflect.i·2+24(SP)
        0x0031 00049 (x.go:6)   MOVQ    reflect.i·2+16(SP), AX
        0x0036 00054 (x.go:6)   TESTQ   AX, AX
        0x0039 00057 (x.go:6)   JEQ     95
        0x003b 00059 (x.go:6)   LEAQ    go.itab.*reflect.rtype,reflect.Type(SB), CX
        0x0042 00066 (x.go:6)   MOVQ    64(CX), CX
        0x0046 00070 (x.go:6)   MOVQ    AX, (SP)
        0x004a 00074 (x.go:6)   PCDATA  $0, $1
        0x004a 00074 (x.go:6)   CALL    CX
        0x004c 00076 (x.go:6)   MOVBLZX 8(SP), AX
        0x0051 00081 (x.go:6)   MOVB    AL, "".~r1+64(SP)
        0x0055 00085 (x.go:6)   MOVQ    32(SP), BP
        0x005a 00090 (x.go:6)   ADDQ    $40, SP
        0x005e 00094 (x.go:6)   RET
        0x005f 00095 (x.go:6)   MOVQ    $0, CX
        0x0061 00097 (x.go:6)   MOVQ    CX, AX
        0x0064 00100 (x.go:6)   JMP     66
        0x0066 00102 (x.go:6)   NOP
        0x0066 00102 (x.go:5)   PCDATA  $0, $-1
        0x0066 00102 (x.go:5)   CALL    runtime.morestack_noctxt(SB)
        0x006b 00107 (x.go:5)   JMP     0
```

Hope this helps a bit,
Kirill

**Comment by kisielk** [comment]
Thanks for the thorough analysis!

As far as panic / recover, I was thinking of just wrapping the map assignment in a function call and having the panic / recover limited to that context. I don't think there would be much danger of it inadvertently catching another panic. The problem I have with reflection is that you are paying the price every single time, just to guard against something that is pretty much an extreme edge case. It's probably worth benchmarking the two approaches to see which one wins out.

**Comment by navytux** [comment]
I agree both ways could work. There is a price with panics too because recover has to be in deferred function and defer is known not to be very fast at the moment.

**Comment by navytux** [comment]
For the reference:

```
kirr@deco:~/src/wendelin/neo/g.neo/src/github.com/kisielk/og-rek$ go test -bench MapSet
goos: linux
goarch: amd64
BenchmarkMapSetReflect-4        20000000                92.0 ns/op
BenchmarkMapSetPanic-4          10000000               137 ns/op
```

```diff
diff --git a/ogorek_test.go b/ogorek_test.go
index c4cfd92..8655b63 100644
--- a/ogorek_test.go
+++ b/ogorek_test.go
@@ -3,6 +3,7 @@ package ogórek
 import (
        "bytes"
        "encoding/hex"
+       "fmt"
        "io"
        "math/big"
        "reflect"
@@ -268,3 +269,51 @@ func TestFuzzCrashers(t *testing.T) {
                dec.Decode()
        }
 }
+
+
+func mapSetReflect(m map[interface{}]interface{}, key, value interface{}) error {
+       if !reflect.TypeOf(key).Comparable() {
+               return fmt.Errorf("mapSet: invalid key type: %T", key)
+       }
+
+       m[key] = value
+       return nil
+}
+
+func mapSetPanic(m map[interface{}]interface{}, key, value interface{}) (err error) {
+       defer func() {
+               if r := recover(); r != nil {
+                       // XXX it is better to check r.Error() to has "unhashable type ..."
+                       err = fmt.Errorf("mapSet: invalid key type: %T", key)
+               }
+       }()
+
+       m[key] = value
+       return nil
+}
+
+func BenchmarkMapSetReflect(b *testing.B) {
+       m := make(map[interface{}]interface{})
+       key := "hello"
+       value := "world"
+
+       for i := 0; i < b.N; i++ {
+               err := mapSetReflect(m, key, value)
+               if err != nil {
+                       b.Fatal(err)
+               }
+       }
+}
+
+func BenchmarkMapSetPanic(b *testing.B) {
+       m := make(map[interface{}]interface{})
+       key := "hello"
+       value := "world"
+
+       for i := 0; i < b.N; i++ {
+               err := mapSetPanic(m, key, value)
+               if err != nil {
+                       b.Fatal(err)
+               }
+       }
+}
```

**Comment by navytux** [comment]
Please also see https://github.com/golang/go/issues/19359 - basically currently after fist panic on non-comparable key map becomes completely unusable.

**Comment by navytux** [comment]
See also: https://github.com/golang/go/issues/19361

**Comment by cwedgwood** [comment]
re: panic performance

Is this an issue right now?  It will only be slow in rare situations for most current users I would think.

If someone does have performance issues as a result of bad-input it could be revisited at the the time.

**Comment by navytux** [comment]
panic performance: please see above for benchmarks where there is no errors and thus no actual panic, but just due to defer it runs slower.

**Comment by cwedgwood** [comment]
@navytux thanks, i see the numbers now

that's a much greater difference than i would have expected

**Comment by kisielk** [comment]
@navytux thanks again for the research. I guess we will use the reflect method in that case. Kind of funny that looking into this resulted in two golang issues though :)

**Comment by navytux** [comment]
@kisielk thanks for feedback. Yes, a bit funny. I hope with simple underlying types tracking thinkgs like `reflect.TypeOf` will be even more faster (no indirect call and no allocation). It is kind of long standing issue for me that in go using interfaces in hot paths makes generated code, sometimes unacceptable, dumb. Let's hope things could be changed for the better.

**Comment by navytux** [comment]
> The unhashable type one is tricky because there's not really a good way to detect whether a type is hashable or not without walking all of its members with reflect, and that's a potentially expensive operation. 

@kisielk, I have to say you were right here - the task to determine whether a type is fully comparable is recursively expensive and must be explicitly programmed as `reflect.Type.Comparable()` is not enough:

```
package main

import "reflect"

func comparable(v interface{}) bool {
        return reflect.TypeOf(v).Comparable()
}

type Ref struct {
        Pid interface{}
}

func main() {
        r := Ref{Pid: []interface{}{1}}
        println(comparable(r)) // -> "true"

        m := make(map[interface{}]interface{})

        // even though r is comparable, `r ==` panics at runtime, because
        // r.Pid's dynamic type is not comparable. The following assignment
        // thus panics.
        m[r] = 2
}
```

```
kirr@deco:~/tmp/trashme$ go run r.go 
true
panic: runtime error: hash of unhashable type []interface {}

goroutine 1 [running]:
main.main()
        /home/kirr/tmp/trashme/r.go:22 +0x1d1
exit status 2
```

-> It seems we better switch all "key not comparable" to panic/recover for correctness. Appologize for convincing you back in 2017 it was not neede.
